site_name: Lietuvos šaulių sąjungos teisės aktai
nav:
  - Pradžia: index.md
  - Etikos Kodeksas: Sauliu-etikos-kodeksas.md
  - LŠS statutas: Lietuvos-sauliu-sajungos-statutas.md
  - LŠS statuto priedai: Lietuvos-sauliu-sajungos-statuto-priedai.md
theme:
  language: lt
  name: 'material'
  #custom_dir: 'theme'
  #palette:
  #  primary: '003334'
  #  accent: 'light green'
  palette: 
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-3
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    #- navigation.sections
    #- navigation.expand

markdown_extensions:
  - pm_attr_list

extra_css:
  - stylesheets/extra.css
#  - stylesheets/codehilite.css

repo_url: https://github.com/LSS-DOK/lss-teises-aktai
repo_name: lss-teises-aktai